export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGOUT = "USER_LOGOUT";

export const DISTRICTS_CALL_REQUEST = "DISTRICTS_CALL_REQUEST";
export const DISTRICTS_CALL_SUCCESS = "DISTRICTS_CALL_SUCCESS";
export const PROVINCES_CALL_REQUEST = "PROVINCES_CALL_REQUEST"
export const PROVINCES_CALL_SUCCESS = "PROVINCES_CALL_SUCCESS"
export const STREETS_CALL_REQUEST = "STREETS_CALL_REQUEST"
export const STREETS_CALL_SUCCESS = "STREETS_CALL_SUCCESS"
export const WARDS_CALL_REQUEST = "WARDS_CALL_REQUEST"
export const WARDS_CALL_SUCCESS = "WARDS_CALL_SUCCESS"

export const DISTRICTS_CALL_REQUEST_POST_NEWS = "DISTRICTS_CALL_REQUEST_POST_NEWS";
export const DISTRICTS_CALL_SUCCESS_POST_NEWS = "DISTRICTS_CALL_SUCCESS_POST_NEWS";
export const PROVINCES_CALL_REQUEST_POST_NEWS = "PROVINCES_CALL_REQUEST_POST_NEWS"
export const PROVINCES_CALL_SUCCESS_POST_NEWS = "PROVINCES_CALL_SUCCESS_POST_NEWS"
export const STREETS_CALL_REQUEST_POST_NEWS = "STREETS_CALL_REQUEST_POST_NEWS"
export const STREETS_CALL_SUCCESS_POST_NEWS = "STREETS_CALL_SUCCESS_POST_NEWS"
export const WARDS_CALL_REQUEST_POST_NEWS = "WARDS_CALL_REQUEST_POST_NEWS"
export const WARDS_CALL_SUCCESS_POST_NEWS = "WARDS_CALL_SUCCESS_POST_NEWS"